### ISSUE TITLE
Change or drop habitat type overlay from sidebar header

### ISSUE THREAD

**Issue by walkerjeffd** [HWR-llc/ett#19]
As discussed in the last meeting, it can be hard to read the sidebar header that is overlayed on top of the image. Always tricky to have text on top of images...

One trick is to add a semi-transparent background to the div containing the text, e.g.:

```css
.overlay-text {
  width: 100%;
  background: rgba(255, 255, 255, 0.5);
  color: 'black';
  padding-left: 15px; /* This is better than `left: 10%` for shifting the text over */
}
```

![image](https://user-images.githubusercontent.com/981144/166612082-ccf4e3a2-7850-486c-be24-e7dd52022344.png)

Or a fancier version could have a gradient, like we did for the splash image on the new [ecosheds](https://www.usgs.gov/apps/ecosheds/) homepage.

But I also thought maybe we don't need the overlay text at all, because the habitat type is also shown in the bar chart title, so there's duplicated text for whichever habitat is selected. Maybe just drop the overlay, and keep the bar chart title.

![image](https://user-images.githubusercontent.com/981144/166611977-7f6b87cc-acd9-464b-acd2-3429c2bc768a.png)
